apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: test-client
spec:
  steps:
  - name: test-client
    image: ubuntu
    command:
    - /bin/bash
    - -c
    args:
    - echo "Testing the client app."