apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-app-task
spec:
  inputs:
    resources:
      # The input resource(s) of the task, such as an image
  steps:
    ...
    # Each step of the task
